[package]
name = "emeraldc-tree-checker"
version = "0.1.0"
edition = "2024"

[dependencies]
emeraldc-parser = { path = "../emeraldc-parser" }
emeraldc-span = { path = "../emeraldc-span" }
emeraldc-lexer = { path = "../emeraldc-lexer" }
