[package]
name = "emeraldc-lexer"
version = "0.1.0"
edition = "2024"

[dependencies]
emeraldc-tokenizer = { path = "../emeraldc-tokenizer" }
emeraldc-span = { path = "../emeraldc-span" }
serde = { version = "1.0.219", features = ["derive"] }
