[package]
name = "emeraldc-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
emeraldc-lexer = { path = "../emeraldc-lexer" }
emeraldc-span = { path = "../emeraldc-span" }
log = "0.4.27"
serde = { version = "1.0.219", features = ["derive"] }
